# MAYCORE_FOUND - may_core was founded
# MAYCORE_INCLUDE_DIR - include directory
# MAYCORE_LIBRARIES - link these to use

INCLUDE(FindPackageHandleStandardArgs)

FIND_LIBRARY(MAYCORE_LIBRARIES may_core)
FIND_PATH(MAYCORE_INCLUDE_DIRS "may/core/lib.h")

FIND_PACKAGE_HANDLE_STANDARD_ARGS(MayCore DEFAULT_MSG MAYCORE_LIBRARIES MAYCORE_INCLUDE_DIRS)
MARK_AS_ADVANCED(MAYCORE_INCLUDE_DIRS)